version: "3"
services:
  ui:
    image: erdaproject/erda-ui:1.0-20210601-0d38983
    container_name: erda-ui
    depends_on:
      - openapi
    env_file:
      - ./env
    environment:
      TA_ENABLE: "true"
      UI_THEME: "dice"
      ENABLE_MPAAS: "false"
      ENABLE_BIGDATA: "false"
      ONLY_FDP: "false"
      TERMINUS_KEY: "123"
      FDP_UI_ADDR: "www.erda.cloud"
    ports:
      - "80:80"
    restart: always
    platform: linux/amd64

  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1.pre.1-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./kratos
        target: /etc/config/kratos
    command:
      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - default

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
    ports:
      - "4455:4455"
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=
      - BASE_URL=http://one.erda.local/uc/
      - KRATOS_BROWSER_URL=http://one.erda.local/.ory/kratos/public/

    networks:
      - default
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1.pre.1-sqlite
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - default

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - default

  kms:
    image: erdaproject/kms:20200608-f11445f776ba50e1f947096f57956a3f0333ab11
    container_name: erda-kms
    depends_on:
      - erda-migration
    env_file:
      - ./env
    ports:
      - "3082:3082"
    restart: always
    platform: linux/amd64

  eventbox:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/eventbox
    container_name: erda-eventbox
    depends_on:
      - erda-migration
    env_file:
      - ./env
    ports:
      - "9528:9528"
    restart: always
    platform: linux/amd64

  pipeline:
    image: erdaproject/pipeline:1.0-20210524-b614087
    command: /app/pipeline
    container_name: erda-pipeline
    depends_on:
      - erda-migration
      - scheduler
    env_file:
      - ./env
    environment:
      DEBUG: "false"
      PIPELINE_STORAGE_URL: file:///devops/storage
    ports:
      - "3081:3081"
    restart: always
    platform: linux/amd64

  ops:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/ops
    container_name: erda-ops
    depends_on:
      - erda-migration
    env_file:
      - ./env
    restart: always
    platform: linux/amd64

  qa:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/qa
    container_name: erda-qa
    env_file:
      - ./env
    environment:
      SONAR_ADMIN_TOKEN: 123456
    ports:
      - "3033:3033"
    depends_on:
      - erda-migration
      - cmdb
    restart: always
    platform: linux/amd64

  scheduler:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/scheduler
    container_name: erda-scheduler
    depends_on:
      - erda-migration
      - etcd
    env_file:
      - ./env
    environment:
      CMDB_CONTAINER_TOPIC: spot-metaserver_container
      CMDB_GROUP: spot_cmdb_group2
      DEBUG: "false"
    ports:
      - "9091:9091"
    restart: always
    platform: linux/amd64

  apim:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/apim
    container_name: erda-apim
    depends_on:
      - erda-migration
    env_file:
      - ./env
    ports:
      - "3083:3083"
    restart: always
    platform: linux/amd64

  cmdb:
    image: erdaproject/cmdb:1.1-20210604-14fa00c
    command: /app/cmdb
    container_name: erda-cmdb
    env_file:
      - ./env
    volumes:
      - type: volume
        source: erda-files
        target: /files
        read_only: false
      - type: volume
        source: erda-avatars
        target: /avatars
        read_only: false
    environment:
      DEBUG: "false"
      ORY_ENABLED: "true"
      KRATOS_ADDR: "kratos:4433"
      KRATOS_PRIVATE_ADDR: "kratos:4434"
      ORY_KRATOS_ADDR: "kratos:4433"
      ORY_KRATOS_PRIVATE_ADDR: "kratos:4434"
    ports:
       - "9093:9093"
    depends_on:
      - erda-migration
      - eventbox
    restart: always
    platform: linux/amd64

  gittar:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/gittar
    container_name: erda-gittar
    depends_on:
      - erda-migration
    env_file:
      - ./env
    volumes:
      - type: volume
        source: erda-gittar
        target: /repository
        read_only: false
    ports:
       - "5566:5566"
    environment:
      GITTAR_SKIP_AUTH_URL: gittar:5566
      ORY_ENABLED: "true"
      KRATOS_ADDR: "kratos:4433"
      KRATOS_PRIVATE_ADDR: "kratos:4434"
      ORY_KRATOS_ADDR: "kratos:4433"
      ORY_KRATOS_PRIVATE_ADDR: "kratos:4434"
    restart: always
    platform: linux/amd64

  gittar-adaptor:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/gittar-adaptor
    container_name: erda-gittar-adaptor
    depends_on:
      - erda-migration
      - gittar
      - pipeline
    env_file:
      - ./env
    ports:
      - "1086:1086"
    restart: always
    platform: linux/amd64

  dicehub:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/dicehub
    container_name: erda-dicehub
    depends_on:
      - erda-migration
    env_file:
      - ./env
    ports:
      - "10000:10000"
    environment:
      EXTENSION_MENU: '{"流水线任务":["source_code_management:代码管理","build_management:构建管理","deploy_management:部署管理","version_management:版本管理","test_management:测试管理","data_management:数据治理","custom_task:自定义任务"],"扩展服务":["database:存储","distributed_cooperation:分布式协作","search:搜索","message:消息","content_management:内容管理","security:安全","traffic_load:流量负载","monitoring&logging:监控&日志","content:文本处理","image_processing:图像处理","document_processing:文件处理","sound_processing:音频处理","custom:自定义","general_ability:通用能力","new_retail:新零售能力","srm:采供能力","solution:解决方案"]}'
      RELEASE_GC_SWITCH: "true"
      RELEASE_MAX_TIME_RESERVED: "72"
    restart: always
    platform: linux/amd64

  openapi:
    image: erdaproject/openapi:1.1-20210602-d2be13e
    command: /app/openapi
    container_name: erda-openapi
    depends_on:
      - redis-sentinel
      - redis
      - erda-migration
      - scheduler
      - pipeline
      - gittar
      - apim
      - cmdb
      - dicehub
      - eventbox
      - gittar-adaptor
      - kms
      - hepa
      - ops
      - orchestrator
      - qa
    env_file:
      - ./env
    environment:
      SELF_PUBLIC_ADDR: "one.erda.local:9529"
      CUSTOM_NAMESPACE: "local"
      ORY_ENABLED: "true"
      KRATOS_ADDR: "kratos:4433"
      KRATOS_PRIVATE_ADDR: "kratos:4434"
      ORY_KRATOS_ADDR: "kratos:4433"
      ORY_KRATOS_PRIVATE_ADDR: "kratos:4434"
      SESSION_COOKIE_NAME: "ory_kratos_session"
    ports:
      - "9529:9529"
    restart: always
    platform: linux/amd64

  hepa:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/hepa
    container_name: erda-hepa
    depends_on:
      - erda-migration
    env_file:
      - ./env
    restart: always
    platform: linux/amd64

  orchestrator:
    image: erdaproject/erda:1.0-20210521-3a995ee
    command: /app/orchestrator
    container_name: erda-orchestrator
    depends_on:
      - erda-migration
      - scheduler
    env_file:
      - ./env
    environment:
      DEBUG: "false"
      TENANT_GROUP_KEY: 58dcbf490ef3
    ports:
      - "8081:8081"
    restart: always
    platform: linux/amd64

  etcd:
    image: bitnami/etcd:3
    container_name: erda-etcd
    volumes:
      - type: volume
        source: erda-etcd
        target: /bitnami/etcd/data
        read_only: false
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    restart: always
    platform: linux/amd64

  mysql:
    image: erdaproject/mysql:5.7-quickstart
    container_name: erda-mysql
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: erda-mysql
        target: /var/lib/mysql
        read_only: false
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: Asia/Shanghai
    restart: always
    platform: linux/amd64

  erda-migration:
    image: erdaproject/erda-mysql-migration-action:20210701-f84c33b
    container_name: erda-migration
    depends_on:
      - mysql
    environment:
      - TZ=Asia/Shanghai
      - MIGRATION_MYSQL_HOST=mysql
      - MIGRATION_MYSQL_PORT=3306
      - MIGRATION_MYSQL_USERNAME=root
      - MIGRATION_MYSQL_PASSWORD=123456
      - MIGRATION_MYSQL_DBNAME=erda
      - MIGRATION_DEBUGSQL=false
      - MIGRATION_ERDA_LINT=true
    volumes:
      - ../.erda/migrations:/migrations
    restart: on-failure
    platform: linux/amd64

  redis-sentinel:
    image: bitnami/redis-sentinel:6.0-debian-10
    container_name: erda-redis-sentinel
    environment:
      REDIS_MASTER_PASSWORD: "123456"
    restart: always
    platform: linux/amd64

  redis:
    image: bitnami/redis:6.0-debian-10
    container_name: erda-redis
    environment:
      REDIS_PASSWORD: "123456"
    ports:
      - "16379:6379"
    restart: always
    platform: linux/amd64
volumes:
  erda-mysql: {}
  erda-etcd: {}
  erda-gittar: {}
  erda-avatars: {}
  erda-files: {}
  kratos-sqlite: {}

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
